language: minimal
dist: xenial
script:
- make tests
deploy:
  provider: script
  script: make publish
  on:
    tags: true
env:
  global:
  - secure: f9duu2/FcLl0lAvQSrAFuway5f4CzOD/hlDE0IBBxBqOdFiuOKcrcPIEnP+lGqARRCtqwzSdUovGC5C5a5UHwHyMsb1jyTmL0/+jtxpzWVX4FPn+pWSCh894BSyrV0e2p/RcsfJGv3fe3em9wsFP08QkTWsGBf8vR74gFpEChVk1EI+5jWwppjXyZ+yS9zobM0cVH7O08j8xsxyG19Qtvb7xkpm4xOzwcESq3Zp/Je6ueQ+2fF16EHVv6zT9atCuEk7ftrKeFgp6LcoFC8zkasz3qlo0vNbuyCX988nDLTw5PQJy1bdf/47XpGjNxgW01ZU/IwfGe440+z7yARbwkVOM7HInJkcfpsBVttRBYTOpm5rnMnZQN74BHb8n3G6O1jq4+hqSTcxsd+9MQqz9oRZDpZaCZVVkbGDFP4YHN6NsT/PDcZM11iJxwtKTE/JiiTG/mg6JTnQQJmUOC2i5Y8LnzEWnjzFhhjoW5VXdUBOP4/g/6xPTKrGoWT+pPkYvto7RlelObvRfN7Rom6EQzbOQv9BIpvEEEOYwHeNbnjDPiavyDofGHpAcqNH7K4r+AY4+bHOBQO5ilalGERHLhoRspfczivnzAiItilkcr+c6eKDsvcZo1ypehR0pRcZ9ZYWV4LJVMag7ZSktX4xX3XdqFZsq1iZZDRmilZILfBw=
  - secure: Pk06zeaGATx3Ryrw1uN5BCFoCV+sdKCGfwjtFYSACEFXR+EodaNsH39YtwVlcwBaTuWyP4kWuaOk7UI0tgJc1oDRfNJ//3/9TVgwWQ/SHEdlLEhxiSY0nfRMNFQwS4X2douT0Vv+KkyBe0NZQAw+oq/NCJJodYwVjxkgQzxZhQePt9RQIKGDp/k18ymSP7WXsSv/af2uxRYlQ59hg/eBP624gPpxshCOeplAfJ2PFVpvcuNx134D9s4JdeI7XbwXLeWpfAKPznFU/L9yzJ+Bgjr1oiUTckU5iKaLC7oPOQoDTWLQyoGXx205cYtdyjXmn7YCqpjZ/gJP13Y3MyS1TFvTEYU9fwOleEy2xdF9/zoJYTUrEz8uVWqdP+1ZiATPqeiF5OzNr2BazLuXWgZRgEvBR9pFnA84B3bgP7D64ycHOXugmg6ReXsfrYUZA9cC+GHxFA3pRk+xy+bXcHGsisbbNBnle0O+Tx98luEY1OTMB0ALF15xOOcX+fPhE6pWA0Uof5M3wWz0dzP3twrIiNlRlM1IDYmPcgcXn/ZCAcFOe4/jUJDjtok4e7abkJH8j6DYR3bAhcSYMB6uzvvc/jOHnIQrvumXC4nLdsQc/H42e0qJSfEIhSfMltr4gKDGWCfLWtZHoRgrSgemhoXsB4F+Tp9fUolE4IuD2lbLTpo=
